version: '3'

services:
  meyer-mind-studio:
    build: .
    env_file: .env
    ports:
      - '12400:8080'
    volumes:
      - backend-public-data:/usr/app/src/public
    restart: unless-stopped

volumes:
  backend-public-data:
