version: '3.8'

services:
  app:
    image: your-docker-hub-username/your-repo-name
    container_name: your-container-name
    ports:
      - '12345:12345'
    environment:
      - NODE_ENV=production